### ISSUE TITLE
イメージビュアー上で右クリックすると次のタブに切り替わる

### ISSUE THREAD

**Issue by vabock** [Hiroyuki-Nagata/JaneClone#46]
MacBookのトラックパッドで右クリックを二本指のタップに設定していると、右クリックイベントの前に`event.m_wheelRotation`が`0`の`OnMouseWheel`イベントが発生してしまうようです。ライブラリ側でなんとかしてほしいところですがとりあえず対策しましょう

**Comment by vabock** [comment]
あと、`JaneCloneImageViewer`の右クリックメニューですが`EVT_RIGHT_DOWN`ではなく`EVT_CONTEXT_MENU`を使ったほうがいいと思います
```diff
--- a/src/imagepanel.cpp
+++ b/src/imagepanel.cpp
@@ -26,7 +26,6 @@
 
 BEGIN_EVENT_TABLE(wxImagePanel, wxPanel)
 
-EVT_RIGHT_DOWN(wxImagePanel::RightClick)
 // some useful events
 /*
   EVT_MOTION(wxImagePanel::mouseMoved)
@@ -108,14 +107,6 @@ void wxImagePanel::Render(wxDC&  dc) {
      dc.DrawBitmap( image, 0, 0, false );
 }
 /**
- * パネル上で右クリックされた場合の処理
- */
-void wxImagePanel::RightClick(wxMouseEvent& event) {
-
-     // 親クラスのイベントを呼ぶ・戻ってこない
-     return ((JaneCloneImageViewer*)this->GetParent())->OnRightClickImageViewer(event);
-}
-/**
  * 画像のファイルパスを返す
  */
 wxString wxImagePanel::GetFilePath() {
```
このイメージパネル側の処理も必要無くなります。ただし、タブが無いときでもメニューが出てしまうので状況によってメニューアイテムを無効化する必要があります。
本来はEVT_UPDATE_UIでやるのが良いのでしょうが今回は"ビューア設定"と"ビューアを隠す"以外のメニュー項目の有効／無効を切り換えるようにしました。今一ならマージから外します(vabock/JaneClone@562b1a983469c557e9bf277f610e370a47935ad3)

もう一つ、`GetPage`で返されるポインタは`wxImagePanel`そのものなので`wxWindow::FindWindowById`を挟む必要はありません(vabock/JaneClone@086f43bf85abe2940d9e295ad9d02ac10cc68983)

**Comment by Hiroyuki-Nagata** [comment]
おおお、これまたありがとうございます
ちょっと今すぐは確認できないので明日･明後日あたり確認します

**Comment by Hiroyuki-Nagata** [comment]
エレガントな書き方です！

画像ビューアにおいて、マウスウィールでタブの切替を行うのはJaneStyleのデフォルトで有効なので実装しておきたいのです。本当はトラックパッドかマウスなのか判定するべきなんでしょうが…後々設定画面で動作を切替えられるようにしましょうか。
