### ISSUE TITLE
ビルトインなライブラリの扱い

### ISSUE THREAD

**Issue by Hiroyuki-Nagata** [Hiroyuki-Nagata/JaneClone#49]
以下のコミットで出た話
454dd11f3bd6a3228564524bf446a95db7efddfa
そもそも共有ライブラリを作る必要がありますか？、ということ。builtinなライブラリはスタティックリンクする方針で。

### 内蔵ライブラリについての方針
* システムのパッケージを使う
  * `libsqlite3`
  * `wxsqlite3`
* builtinをスタティックリンク
  * `curlpp`
    * sid(unstable)にしかパッケージがないため
    * Fedora 21には`curlpp-devel-0.7.3-19.fc21`がある
  * `libctw`

### Ubuntu, Fedora, Debian, MinGW, Macの場合についてどのように対応するか？
プラットフォーム　　　　| libsqlite3  | libwxsqlite3 | curlpp |
------------------------------------|--------------|-----------------|----------|
Ubuntu                                | sys          | sys              | bultin  |
Fedora                                | sys          | sys              | sys      | 
Debian                                | sys          | sys              | builtin  | 
MinGW                                | bultin      | builtin          | builtin  | 
Mac                                     | sys          | builtin         | builtin  | 

### crossguidは？

`crossguid`については画像キャッシュのファイル名作成用途だけでは、ちょっと大袈裟だと思うので別のやり方を考えた上で削除しましょう(とりあえず思い付くのは`libssl`のMD5ハッシュを使ってURLからファイル名を作るとか)

この話は #1 につながる。仕様も含めてまだ検討中です。

**Comment by Hiroyuki-Nagata** [comment]
若干ミスった

staticリンクに関しては、 以下のようにすれば動いてくれるかなあ
staticのフラグを制御しないといけない（全体がstaticリンクにならないようにする）。
https://www.sourceware.org/autobook/autobook/autobook_89.html

```
bin_PROGRAMS  = shell
shell_SOURCES = shell.c token.l
shell_LDADD   = libshell.la
LDFLAGS = -static
```

**Comment by vabock** [comment]
crossguidの代替について実装してみました。
* vabock/JaneClone@c59438a6743474e2f5b70280f7fb858e4d0e7233

画像ファイルのURLからハッシュを作ってファイル名に使用します。ライブラリには`libcurl`にも使われている`OpenSSL`の`libcrypto`を利用します。MD5についてはフリーの実装がいくつかあるのですが、多くの実装で採用されているRSAライセンスがGPLとコンパチではないのでメジャーな外部ライブラリにしました。OSXについてはlibcrypto互換のCommonCryptoというライブラリが標準で用意されているのでそちらを使います。

画像URLからキャッシュのファイル名が一意に定まるのでDBに登録する必要が無くなるかもしれません

**Comment by Hiroyuki-Nagata** [comment]
@vabock 
crossguidの変更をマージしました
ここ重要ですね
`画像URLからキャッシュのファイル名が一意に定まるのでDBに登録する必要が無くなるかもしれません`

**Comment by Hiroyuki-Nagata** [comment]
プラットフォーム　　　　| libsqlite3  | libwxsqlite3 | curlpp |
------------------------------------|--------------|-----------------|----------|
Ubuntu                                | sys          | sys              | bultin  |
Fedora                                | sys          | sys              | sys      | 
Debian                                | sys          | sys              | builtin  | 
MinGW                                | bultin      | builtin          | builtin  | 
Mac                                     | builtin      | builtin         | builtin  |

**Comment by vabock** [comment]
Macでシステムの`libsqlite3`を使わないのはなぜですか?
```
$ ls -l /usr/lib/libsqlite3.dylib
-rwxr-xr-x 1 root wheel 4608336  9 18 14:38 /usr/lib/libsqlite3.dylib
```

あと、Fedoraで`wxsqlite3`の検出に失敗します
```
configure:17963: checking for wxsqlite3
configure:17984: g++ -o conftest -g -O0 -DUNICODE   -I/usr/lib64/wx/include/gtk2-unicode-release-2.8 -I/usr/include/wx-2.8 -D_FILE_OFFSET_BITS=64 -D_LARGE_FILES -D__WXGTK__  conftest.cpp -lz -lxml2  -pthread -Wl,-z,relro   -lwx_gtk2u_richtext-2.8 -lwx_gtk2u_aui-2.8 -lwx_gtk2u_xrc-2.8 -lwx_gtk2u_qa-2.8 -lwx_gtk2u_html-2.8 -lwx_gtk2u_adv-2.8 -lwx_gtk2u_core-2.8 -lwx_baseu_xml-2.8 -lwx_baseu_net-2.8 -lwx_baseu-2.8  -lwxsqlite3-2.8 >&5
/bin/ld: cannot find -lwxsqlite3-2.8
collect2: error: ld returned 1 exit status
configure:17984: $? = 1
```
```
$ pkg-config --libs wxsqlite3-2.8
-lwxcode_gtk2_wxsqlite3-2.8
```

**Comment by Hiroyuki-Nagata** [comment]
@vabock 

`Macでシステムのlibsqlite3を使わないのはなぜですか?`
TravisのosxビルドでSQLite3のバージョンが原因のエラーが起きており、そこの面倒を見たくないからです。
https://travis-ci.org/Hiroyuki-Nagata/JaneClone/jobs/47231801
このへん
```
/usr/include/sqlite3.h:4711:16: note: 'sqlite3_enable_shared_cache' has been explicitly marked deprecated here
SQLITE_API int sqlite3_enable_shared_cache(int) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_7, __IPHONE_2_0, __IPHONE_5_0);
```

`あと、Fedoraでwxsqlite3の検出に失敗します`
ごめん、そこまで見きれてないです…
修正できるのであれば歓迎です。
OpenBuildServiceが使えたらもう少しいろんなプラットフォームの面倒が見れるんですけどね。
https://build.opensuse.org/

**Comment by Hiroyuki-Nagata** [comment]
あとcurlppはstaticライブラリにするのが難しいですね。
libcurlpp.aとlibinternal.aで相互に参照しあってるみたい。

**Comment by vabock** [comment]
エラーじゃなくてwarningです
```
wxsqlite3.cpp:2446:12: warning: 'sqlite3_enable_shared_cache' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
```
ソースを読みましたが無視しても問題なさそう。その後のリンクエラーは`-lsqlite3`が指定されていないからです。他の環境でもBuiltinの`wxsqlite3`を使うと同様のエラーが出ます

**Comment by Hiroyuki-Nagata** [comment]
`その後のリンクエラーは-lsqlite3が指定されていないからです。`
そういうことか…ということは、Macの場合に強制的にbultinにするのをやめて、wxsqlite3のビルド時にちょっと細工が必要ですね。

**Comment by Hiroyuki-Nagata** [comment]
Travis版Macバイナリもとりあえず動く状態にはなった。
