### ISSUE TITLE
設定ダイアログのタイムアウト初期値の単位がミリ秒になっている

### ISSUE THREAD

**Issue by vabock** [Hiroyuki-Nagata/JaneClone#51]
設定値の単位は秒なのにダイアログの初期値がミリ秒
![設定 - 通信](https://cloud.githubusercontent.com/assets/481070/5691424/2711f33c-9909-11e4-8d5d-ea2c3645728e.png)

**Comment by Hiroyuki-Nagata** [comment]
https://github.com/Hiroyuki-Nagata/JaneClone/blob/master/src/socketcommunication.cpp#L2452-2460

- curlの設定はミリ秒単位なので、画面の表示を直した方がよい仕様かもしれない
